### ISSUE TITLE
imu.txt in empty

### ISSUE THREAD

**Issue by kxch928925819** [hku-mars/FAST_LIO#49]
dji@dji-B85MG:~/catkin_ws/src/FAST_LIO/Log$ python plot.py 
plot.py:37: UserWarning: loadtxt: Empty input file: "imu.txt"
  imu=np.loadtxt('imu.txt')
Traceback (most recent call last):
  File "plot.py", line 38, in <module>
    time=imu[:,0]
IndexError: too many indices for array
dji@dji-B85MG:~/catkin_ws/src/FAST_LIO/Log$ python3 plot.py 
Traceback (most recent call last):
  File "plot.py", line 25, in <module>
    axs[j%4, j/4].plot(time, a_pre[:,i+j*3],'.-', label=lab_pre[i])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
dji@dji-B85MG:~/catkin_ws/src/FAST_LIO/Log$ code ..

**Comment by kxch928925819** [comment]
dji@dji-B85MG:~/catkin_fastlio_slam/src/FAST_LIO_SLAM/FAST-LIO/Log$ python2 plot.py 
plot.py:37: UserWarning: loadtxt: Empty input file: "imu.txt"
  imu=np.loadtxt('imu.txt')
Traceback (most recent call last):
  File "plot.py", line 38, in <module>
    time=imu[:,0]
IndexError: too many indices for array
dji@dji-B85MG:~/catkin_fastlio_slam/src/FAST_LIO_SLAM/FAST-LIO/Log$ python2.7 p
plot.py      pos_log.txt  
dji@dji-B85MG:~/catkin_fastlio_slam/src/FAST_LIO_SLAM/FAST-LIO/Log$ python2.7 plot.py 
plot.py:37: UserWarning: loadtxt: Empty input file: "imu.txt"
  imu=np.loadtxt('imu.txt')
Traceback (most recent call last):
  File "plot.py", line 38, in <module>
    time=imu[:,0]
IndexError: too many indices for array
dji@dji-B85MG:~/catkin_fastlio_slam/src/FAST_LIO_SLAM/FAST-LIO/Log$
